
# Fields to retrieve from loads collection
LOAD_PROJECTION = {
    "_id": 1,
    "reference_number": 1,
    "containerNo": 1,
    "status": 1,
    "loadStatus": 1,
    "carrier": 1,
    "type_of_load": 1,
    "terminal": 1,
    "availableDate": 1,
    "callerName": 1,
    "shipperName": 1,
    "consigneeName": 1,
    "emptyOriginName": 1,
    "hazmat": 1,
    "hot": 1,
    "liquor": 1,
    "lastFreeDay": 1,
    "containerAvailableDay": 1,
    "emptyDay": 1,
    "pickupTimes": 1,
    "deliveryTimes": 1,
    "returnFromTime": 1,
    "returnToTime": 1,
    "dischargedDate": 1,
    "freeReturnDate": 1,
    "cutOff": 1,
    'containerAvailableDay': 1,
    "driverOrder": 1,
    "driverOrderId": 1,
    "totalMiles": 1,
    "containerSize": 1,
    "containerType": 1,
    "containerSizeName": 1,
    "totalWeight": 1,
    "outgateDate": 1,
    "chassisPickName": 1,
    "consigneeAddress": 1,
    "containerTypeName": 1, 
    "containerOwnerName": 1,
    "caller": 1,
    "freight": 1,
    "distance": 1,
    "isReadyForPickup": 1,
    "isHot": 1,
    "overWeight": 1,
    "caller": 1
}

DISPATCHED_STATUSES = [
    'PENDING',
    'AVAILABLE',
    'DISPATCHED',
    'CHASSISPICK_ARRIVED',
    'CHASSISPICK_DEPARTED',
    'PULLCONTAINER_ARRIVED',
    'PULLCONTAINER_DEPARTED',
    'DELIVERLOAD_ARRIVED',
    'DELIVERLOAD_DEPARTED',
    'RETURNCONTAINER_ARRIVED',
    'RETURNCONTAINER_DEPARTED',
    'DROPCONTAINER_ARRIVED',
    'DROPCONTAINER_DEPARTED',
    'HOOKCONTAINER_ARRIVED',
    'HOOKCONTAINER_DEPARTED',
    "CHASSISTERMINATION_ARRIVED",
    "CHASSISTERMINATION_DEPARTED",
    'STOPOFF_DEPARTED', 
    'STOPOFF_ARRIVED',
]

LOAD_PROJECTION_FOR_OPTIMIZER = {
    "_id": 1,
    "reference_number": 1,
    "type_of_load": 1,
    "carrier": 1,
    "status": 1,
    "temperature": 1,
    "genset": 1,
    "hazmat": 1,
    "hot": 1,
    "isStreetTurn": 1,
    "liquor": 1,
    "domestic": 1,
    "scale": 1,
    "ev": 1,
    "waste": 1,
    "gdp": 1,
    "isRail": 1,
    "oog": 1,
    "bonded": 1,
    "routeType": 1,
    "distance": 1,
    "weight": 1,
    "pallets": 1,
    "pieces": 1,
    "lastFreeDay": 1,
    "emptyDay": 1,
    "loadTime": 1,
    "cutOff": 1,
    "return": 1,
    "freeReturnDate": 1,
    "pickupTimes": 1,
    "deliveryTimes": 1,
    "returnFromTime": 1,
    "returnToTime": 1,
    "dischargedDate": 1,
    "outgateDate": 1,
    "ingateDate": 1,
    "containerNo": 1,
    "chassisNo": 1,
    "chassisId": 1,
    "driverOrder": 1,
    "driverOrderId": 1,
    "isloadStartable": 1,
    "isReadyForPickup": 1,
    "isHot": 1,
    "containerAvailableDay": 1,
    "streetTurn": 1,
    "streetTurnType": 1,
    "totalWeight": 1,
    "totalMiles": 1,
    "destinationETA": 1,
    "overWeight": 1,
    "overHeight": 1,
    "preSetOrderStatus": 1,
    "callerName": 1,
    "shipper": 1,
    "shipperName": 1,
    "shipperAddress": 1,
    "consignee": 1,
    "consigneeName": 1,
    "consigneeAddress": 1,
    "customerEmployee": 1,
    "chassisPick": 1,
    "chassisPickName": 1,
    "emptyOrigin": 1,
    "emptyOriginName": 1,
    "chassisTermination": 1,
    "chassisTerminationName": 1,
    "containerSize": 1,
    "containerType": 1,
    "containerSizeName": 1,
    "containerTypeName": 1,
    "containerOwnerName": 1,
    "chassisTypeName": 1,
    "chassisSizeName": 1,
    "chassisOwnerName": 1,
    "terminal": 1,
    "terminalName": 1,
    "lastUpdatedStatusAt": 1,
    "loadCompletedAt": 1,
    "availableDate": 1,
    "assignedCSR": 1,
    "orderId": 1,
    "isGenset": 1,
    "readyToReturnDate": 1,
    "loadStatus": 1,
    "caller": 1
}
